version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: registros_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: registros_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d registros_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: registros_api
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/registros_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: